### ISSUE TITLE
series id making things too easy

### ISSUE THREAD

**Issue by SammySteiner** [learn-co-curriculum/sql-library-lab#17]
Having a series_id for the characters table makes the 3 join challenge of the following query unnecessary, as demonstrated by the solutions below (intended solution first, followed by alternate solution).  Also, having a series id for characters means that characters can have cameos in other series...

I suggest refactoring the character table schema, the insert, and the data to remove the series_id from the character table.

def select_series_title_with_most_human_characters
  <<-SQL
    SELECT series.title 
    FROM series 
    JOIN books 
    ON books.series_id = series.id 
    JOIN character_books 
    ON character_books.book_id = books.id 
    JOIN characters 
    ON character_books.character_id = characters.id 
    WHERE characters.species = 'human' 
    GROUP BY series.title 
    ORDER BY COUNT(*) DESC 
    LIMIT 1
  SQL
end

Can be solved with:
def select_series_title_with_most_human_characters
  "SELECT series.title
  FROM series
  INNER JOIN characters
  ON series.id = characters.series_id
  WHERE characters.species = 'human'
  GROUP BY series.id
  ORDER BY COUNT(characters.species = 'human') DESC
  LIMIT 1
  "
end

**Comment by maxwellbenton** [comment]
Hi @SammySteiner,

Thank you for opening this issue. We've updated this lesson and incorporated changes based on your feedback, removing series_id from the characters table and adjusting the tests and seed data accordingly so that the expected solution is the only one that will work.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
